name: Push Docker Image to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          dockerfile: Dockerfile
          tags: docker.io/miahoot/miahoot-front2:latest
      
      - name: Pull Docker image
        run: docker pull docker.io/miahoot/miahoot-front2:latest
      
      - name: Tag Docker image
        run: docker tag docker.io/miahoot/miahoot-front2:latest docker.io/miahoot/miahoot-front2:latest
      
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/miahoot/miahoot-front2:latest
